
# https://github.com/nim-lang/Nim/wiki/BuildServices#using-choosenim
language: c

branches:
  only:
    - master

cache: ccache
cache:
  directories:
    - .cache
    - ~/.choosenim/
    - ~/.nimble/

matrix:
  include:
    - os: linux
      env:
        - NAME=LINUX
        - CHANNEL=devel
      compiler: gcc

    - os: osx
      env:
        - NAME=OSX
        - CHANNEL=devel
      compiler: clang

addons:
  apt:
    packages:
      - build-essential

before_install:
  - git tag "$(date +'%Y%m%d%H%M')_$CHANNEL"
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim $CHANNEL

script:
  - make release NAME=$NAME

deploy:
  provider: releases
  api_key:
    secure: HAbMeLDgmMXmqrGlr6wFbu3vmEgY9JoeEEQi+XE15uLsbtKFnAocdb2iZRmqAIBu7EAHuKkgmCn6c6aGQ9UzLcy4dzdNqiBo/6G9IIdJkxMkpF7rQUzyUznV0zz3MPB+SFaGOVI//wz51F8KrZu1fkewC1kD1IWvLrA1lk8+GMXjb1v8XlcT9s5br3IbJ/UWL74CHAfoYx+ez4G8STdzkDTswm4HjxDbKpTn8nmt7tV7+A0fDDZ9SCg4kP44aPard9iyh4TT+e+DMrVTL7wZQ+70QvWkyOKKQDj5tTIHUoiqFRsdqY6cycgTobmr6HdA53IzW+NFclvhSLUBWPzX+zPk4yDgunPqU5KneYrrLzBCzXrWUggrsxYXXlnafjGwJObhw8ZpfNxXZAq1LBs95YZHLV9MHcdV+By9/bFlpsRKaF1w/OpS8XnnkI/y5Wo9abhLYwoMdfQbPckMUUb1XqB7t69lRjdQbC8tGFKLK+2MtJX7RcXmBNAXaeVgaAB0utYmKAy8FGzj4hHKpb5Gs3NuHUQ+UwgBS6Vt2eNHw9zjicOw6CFeLeTksZsD+prxiaT/PFipmkDum4cDjzMisuoIHaWxMHL2MmyZQNGWlvO6ooBRa0rWKdVP6j0g/PLIPb6elelfs4zFlQQQA6GTrhL49bbii2kFwGyhECkya7M=
  file: "tinylog-$NAME.tar.gz"
  skip_cleanup: true
  on:
    repo: Mobilpadde/tinylog
